# Generated by Django 4.2.29 on 2026-03-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.cohort'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.module'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student'),
        ),
    ]
